### ISSUE TITLE
Enabling saving files without downloading them first

### ISSUE THREAD

**Issue by kevgathuku** [pwnall/dropship-chrome#8]
Hello,
Thanks for this awesome extension :+1: 
Would you consider adding support for the recently added [save_url](https://www.dropbox.com/developers/core/docs#save-url) endpoint that enables downloading files directly to Dropbox?
This is much better since it doesn't download the file to the user's computer first.
There's a good write up on it on the [Dropbox Developer blog](https://blogs.dropbox.com/developers/2015/06/programmatically-saving-a-url-to-dropbox/)

**Comment by pwnall** [comment]
@kevgathuku Thanks for the suggestion!

Unfortunately, `save_url` isn't a perfect replacement, because it would fetch the file without Chrome's HTTP headers, such as `Cookie`. This would cause the extension to fail in subtle ways, for example if you try to save a PDF statement from your bank.

Furthermore, even if `save_url` would support custom HTTP headers, replicating Chrome's HTTP headers is non-trivial, both in terms of implementation and security implications. For example, would you be OK with Dropbox getting your bank's session cookie when you save a PDF statement?

**Comment by kevgathuku** [comment]
Hi @pwnall Thanks for the clear explanation.
I now understand that `save_url` would not work for every situation. 
My major concern was when saving large files to Dropbox, where downloading the file first would consume a lot of bandwidth.
But I think I can use alternative solutions for that.
Thanks once again.
